
#include "Can.h"                          /* Standard AUTOSAR CAN definitions, structures, and APIs */
#include "CanIf.h"                        /* Header for reporting received packets and transmit confirmations */
#include "hal_data.h"                     /* Renesas FSP generated structures like g_can_ctrl and g_can_cfg */
#include <string.h>                       /* Provides standard string functions like memset for clearing memory */
#include <stdint.h>                       /* FINAL FIX 1: Explicitly includes uintptr_t type definitions */
/* Corrected initialization format for a single variable tracking the hardware state */
static Can_ControllerStateType Can_ControllerState = CAN_CS_UNINIT;

/* ============================================================================
 * 1. MCAL CAN CONTROLLER INITIALIZATION LAYER
 * ============================================================================ */
// deleted init function from here causing multiple definitions

/* ============================================================================
 * 2. MCAL CONTROLLER MODE DIRECTION LAYER
 * ============================================================================ */
// deleted
/* ============================================================================
 * 3. MCAL DOWNSTREAM PACKET ROUTING & STRUCT TRANSLATION LAYER
 * ============================================================================ */
Std_ReturnType Can_Write(Can_HwHandleType Hth, const Can_PduType* PduInfo)
{
    can_frame_t renesas_frame;            /* Allocates a local hardware-compliant CAN frame on the stack */
    fsp_err_t err;                        /* Local storage variable to review the return value from the MCU hardware */

    /* Added safety check to reject processing if the incoming configuration pointer is empty */
    if (PduInfo == NULL)
    {
        return E_NOT_OK;
    }

    /* Rejects transmission instantly if the incoming data length breaks classic CAN boundaries */
    if (PduInfo->length > 8U)
    {
        return E_NOT_OK;
    }

    /* Rejects transmission requests if the specific controller channel isn't completely online */
    if (Can_ControllerState != CAN_CS_STARTED)
    {
        return E_NOT_OK;
    }

    /* Wipes out random memory junk from the frame structure to guarantee clear flags */
    memset(&renesas_frame, 0, sizeof(can_frame_t));

    /* Extracts the network message ID from the AUTOSAR Pdu layout directly into the hardware container */
    renesas_frame.id = PduInfo->id;
    
    /* Assigns the checked, validated length configuration directly to the hardware frame container */
    renesas_frame.data_length_code = PduInfo->length;
    
    /* Decodes the AUTOSAR mask format to verify if the frame utilizes Extended (29-bit) addressing */
    if ((PduInfo->id & 0x80000000U) != 0U)
    {
        /* Strips out the upper management identification bit utilized by the AUTOSAR layer */
        renesas_frame.id &= 0x1FFFFFFFU; 
        /* Targets the correct field id_mode to specify a 29-bit Extended layout */
        renesas_frame.id_mode = CAN_ID_MODE_EXTENDED;
    }
    else
    {
        /* Targets the correct field id_mode to specify an 11-bit Standard layout */
        renesas_frame.id_mode = CAN_ID_MODE_STANDARD;
    }
    
    /* Explicitly configures the structure to represent a standard Data transmission frame */
    renesas_frame.type = CAN_FRAME_TYPE_DATA;

    /* Loops through the source buffer up to the validated limit of the data payload */
    for (uint8_t i = 0U; i < PduInfo->length; i++)
    {
        /* Transfers single-byte payload segments from the AUTOSAR data array to the hardware cache */
        renesas_frame.data[i] = PduInfo->sdu[i];
    }

    /* Converts the Hardware Transmit Handle directly into the target Renesas Mailbox index */
    uint32_t target_mailbox = (uint32_t)Hth;

    /* Direct execution: Invokes the low-level Renesas FSP library to load data into the hardware registers */
    err = R_CAN_Write(&g_can_ctrl, target_mailbox, &renesas_frame);

    /* Examines if the peripheral accepted and locked the message inside the transmission mailbox */
    if (FSP_SUCCESS == err)
    {
        return E_OK;
    }
    
    return E_NOT_OK;
}

/* ============================================================================
 * 4. UPSTREAM HARDWARE INTERRUPT CALLBACK CALLBACK LAYER
 * ============================================================================ */
void can_callback(can_callback_args_t *p_args)
{
    /* Safety catch: Exits instantly if the hardware ISR supplies an invalid, empty pointer */
    if (p_args == NULL) return;

    /* Evaluates the precise asynchronous event generated by the CAN silicon peripheral */
    switch (p_args->event)
    {
        case CAN_EVENT_RX_COMPLETE:
            /* Confirms data frame actually exists before dereferencing to prevent hardfault */
           
            
                /* Forwards data upward into the AUTOSAR CanIf block using a default index of 0 */
                CanIf_RxIndication(
                    0,                                          /* Simplifies tracking by assigning a default RX PDU ID of 0 */
                    (Can_IdType)p_args->frame.id,            /* Delivers the unique CAN ID read from the network lines */
                    (uint8)p_args->frame.data_length_code,   /* Delivers the byte counter value extracted from the frame */
                    (const uint8 *)p_args->frame.data        /* Delivers the exact pointer tracking the received data buffer */
                );
            
            break;

        case CAN_EVENT_TX_COMPLETE:
            /* Pulls the saved TxPduId context from the pointer to clear the tracking queue */
            CanIf_TxConfirmation(0);
            break;

        default:
            /* Quietly handles or skips any remaining notifications like hardware warnings or bus errors */
            break;
    }
}
